Feat: set kakao map SDK
mash-up-kr/VitaminC_Web pull request #18
Opened 2024-06-20 09:02 UTC by Pridesd

## Issue Number

#17

## Description

> 구현 내용 및 작업한 내용
카카오 지도 사용을 위해 kakao javascript key 연결 및 SDK 설정을 했습니다. 
또한, 테스트 화면을 위해 KakaoMap 컴포넌트를 생성했습니다.

- [x] kakao map script 추가
- [x] KakaoMap 컴포넌트 생성
- [x] 클릭 시 마커 생성 기능 적용 

## To Reviewers

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- KakaoMap의 경우 props(디자인, 함수)나 내부 로직을 따로 설정하지 않았습니다. 추후 논의가 필요해보입니다.
- map을 생성할 때 id를 기준으로 생성하는데 map을 다양한 화면에서 사용하는 경우 이 방법이 맞나 고민이 듭니다.

## Checklist

> PR 등록 전 확인한 것

- [ ] 올바른 타켓 브랜치를 설정하였는가
- [x] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat: add login page`)
- [x] Description에 PR을 구체적으로 설명했는가

2024-06-20 13:20 UTC, poiu694 requested changes
현재 디자인이나 개발 명세가 제대로 나오지 않아서 애매하긴 하지만요!

개발 자체를 할 수는 없지만 DB ERD나 kakao map api 명세가 따로 있으니까 전체적으로 더 개발하기 편한 구조를 만들어 보는 건 어떨까요? 단순히 로드만 하기에는 충분히 추상화 할 수 있는 부분들이 많아보여서요!

scaffold를 잡고 있는거니까 미리 필요한 부분들은 넣어두는게 좋지 않을까 싶어요! 나중에 추가 공수가 안들게요!

2024-06-20 13:20 UTC, poiu694 commented on src/app/layout.tsx
> +declare global {
declare 파일은 `dts` 만드는게 낫지 않을까요?

2024-06-20 13:20 UTC, poiu694 commented on src/app/layout.tsx
> +    kakao: any
`kakao`에서 쓰는 부분이라도 any말고 타입을 지정하는게 좋지 않을까요?

2024-06-20 13:20 UTC, poiu694 commented on src/app/layout.tsx
> +        <script
`Next.js`에서 제공하는 `Script` 컴포넌트 써도 좋지 않을까요?

2024-06-20 13:20 UTC, poiu694 commented on src/app/layout.tsx
> +        ></script>
자식이 없으면 `self-closing` 하는건 어떨까요?

2024-06-20 13:20 UTC, poiu694 commented on src/components/KakaoMap.tsx
> +import React from 'react'
트리쉐이킹이 된다고 하더라도, 불필요한 작업들이 많아질 것 같아서 개발단부터  명시적으로 import는 어떨까요??

2024-06-20 13:20 UTC, poiu694 commented on src/components/KakaoMap.tsx
> +      var container = document.getElementById('map')
`var` 쓴 이유가 있을까요?

2024-06-20 13:20 UTC, poiu694 commented on src/components/KakaoMap.tsx
> +      var container = document.getElementById('map')
실제 DOM으로 작업한 이유가 있을까요? ref로는 안되나요?

2024-06-20 13:20 UTC, poiu694 commented on src/components/KakaoMap.tsx
> +        center: new window.kakao.maps.LatLng(33.450701, 126.570667),
나중에 현재 위치를 받아야 할 것 같은데, 현재 기기 디바이스의 위치 관련 정보를 초기값으로 주는게 좋지 않을까요?

2024-06-20 13:20 UTC, poiu694 commented on src/components/KakaoMap.tsx
> +        level: 3,
3은 어떤걸 의미하나요? 선언적으로 사용하는건 어떨까요?

2024-06-20 13:20 UTC, poiu694 commented on src/components/KakaoMap.tsx
> +      // 지도를 클릭한 위치에 표출할 마커입니다
필요한 주석일까요? 코드로 봐도 이해가 될 것 같아서요!

2024-06-20 13:20 UTC, poiu694 commented on src/components/KakaoMap.tsx
> +      window.kakao.maps.event.addListener(
useEffect에서 너무 많은 작업을 하는 것 같아요. 책임을 분리하는건 어떨까요?

1. map load
2. marker 생성
3. event 관리

2024-06-20 13:20 UTC, poiu694 commented on src/components/KakaoMap.tsx
> +        function (mouseEvent: {
저희 arrow function이 코드 스타일 규칙인 것 같아요~

2024-06-20 13:20 UTC, poiu694 commented on src/components/KakaoMap.tsx
> +  //
이 부분은 어떤건가요?

2024-06-20 13:20 UTC, poiu694 commented on src/components/KakaoMap.tsx
> +    <section id="map" style={{ width: '400px', height: '400px' }}></section>
여기도 마찬가지로 `self-closing` 하면 좋을 것 같아요.

2024-06-20 13:20 UTC, poiu694 commented on src/components/KakaoMap.tsx
> +const KakaoMap = () => {
KakaoMap의 컴포넌트 역할이 너무 많지 않나 싶어요! kakao map을 로딩하는 것부터 너무 많은 역할을 하게 될 것 같아요. 추상화 수준을 조금 높이면 어떨까요?

가령 아래처럼 쓸 수 있게요.

```tsx
<Map>
  <Markers ... />
  <Overlay ... />
  <그 외 필요한 컴포넌트 ... />
</Map>
```

2024-06-20 13:21 UTC, poiu694 commented
추가로 프리뷰 커멘트 들어가보시면 script가 제대로 삽입 안되서 오류가 터지는 것 같은데, PR 올릴 때마다 작업사항 확인 부탁드려요!~

2024-06-22 09:43 UTC, hee-suh requested changes
이미 꼼꼼하게 달려있는 리뷰에 동의만 잔뜩 했네요...! 요청 사항 반영해주시면 빠르게 리뷰해보도록 하겠습니다~!

2024-06-22 09:43 UTC, hee-suh commented on src/app/layout.tsx
> +        ></script>
저도 `self-closing`이 좋을 것 같습니다~!

2024-06-22 09:43 UTC, hee-suh commented on src/components/KakaoMap.tsx
> +import React from 'react'
저도 `import { useEffect } from 'react'` 처럼 명시적으로 import 하는게 좋을 것 같습니다!

2024-06-22 09:56 UTC, hee-suh commented on src/components/KakaoMap.tsx
파일명 컨벤션을 [kebab-case](https://developer.mozilla.org/en-US/docs/Glossary/Kebab_case)로 가져가는 건 어떨까요?

2024-06-23 08:26 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +  //
이 부분은 해당 컴포넌트의 최종적으로 return 되는 부분을 표시하는 용도로 사용하는 건데요! 이거를 사용하면 어떤 값을 return하는지 쉽게 파악할 수 있어 사용하는 방법입니다. 습관처럼 사용하던 방법이라 이 부분은 지우겠습니다!

2024-06-23 09:17 UTC, Pridesd commented on src/app/layout.tsx
> +declare global {
73f7e2856f1a805f48cc6886064640c360388d9c

https://github.com/JaeSeoKim/kakao.maps.d.ts/blob/master/%40types/LatLng.d.ts 의 코드에서 현재 사용중인 부분만 추출했습니다. 

추출하면서 드는 생각이 앞으로 다른 기능을 사용하게 되는 경우 다시 type을 추가해야 할텐데 굳이 type을 직접 지정하기 보다 위 라이브러리를 사용하면 되지 않을까 생각이 드는데 어떻게 생각하시나요? @hee-suh

2024-06-23 09:18 UTC, Pridesd commented on src/app/layout.tsx
> +    kakao: any
73f7e2856f1a805f48cc6886064640c360388d9c

위와 동일합니다!

2024-06-23 09:18 UTC, Pridesd commented on src/app/layout.tsx
> +        <script
42472afc6e6b3baec0265690f040bc8b0f4fd857

next에서 Script를 제공해주는군요! 적용했습니다!

2024-06-23 09:19 UTC, Pridesd commented on src/app/layout.tsx
> +        ></script>
42472afc6e6b3baec0265690f040bc8b0f4fd857

self-closing 적용했습니다!

2024-06-23 09:21 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +import React from 'react'
9f2198cf623e7de84c71b26b72d07356bdac0f82

저는 React에서 제공하는 hook들은 React로 import하는 게 더욱 가독성이 좋다고 생각해서 React hook의 경우에는 항상 저렇게 사용했었는데 오히려 더 복잡하게 만들 수도 있나보군요! 수정했습니다!

2024-06-23 09:22 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +      var container = document.getElementById('map')
bd1cc0911b60279ddb4baa7cfdff99ea75717e6d

이 부분은 카카오 문서를 그대로 따라 쓰다가 실수한 부분입니다 ㅠ 수정했습니다!

2024-06-23 09:22 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +      var container = document.getElementById('map')
bd1cc0911b60279ddb4baa7cfdff99ea75717e6d

위와 동일하게 카카오 문서를 따라 쓰다가 실수한 부분입니다 ㅠ

2024-06-23 09:23 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +        level: 3,
a15edf48c4aca905a0fda5c449287f47c9607bf8

이거도 카카오문서.. 
props로 받는 걸로 변경했습니다.

2024-06-23 09:24 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +      // 지도를 클릭한 위치에 표출할 마커입니다
9f2198cf623e7de84c71b26b72d07356bdac0f82
81314c729eaf4153af4e58792bfaa0618cbee1ea

제거했습니다!

2024-06-23 09:26 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +        function (mouseEvent: {
bd1cc0911b60279ddb4baa7cfdff99ea75717e6d

2024-06-23 09:26 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +  //
89092ee12940bf7713c6bc696181dc597aec118d

2024-06-23 09:26 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +    <section id="map" style={{ width: '400px', height: '400px' }}></section>
6edd787616b12079b80626949b1504b91cb32c00

2024-06-23 09:27 UTC, Pridesd commented on src/components/KakaoMap.tsx
63e36b8a50485a93e277faeb650903aaf8176afc

next에서는 kebab case를 따르고 있는 걸 이번에 알았네요! (아 케밥 먹고 싶다) 왜 next에선 kebab case를 따르고 있는지 궁금하네요!

2024-06-23 13:53 UTC, hee-suh commented on src/app/layout.tsx
> +declare global {
업데이트 주기가 짧지 않기도 하고 안정성 보장이 된다고 하기도 어려워서, 위 소스 코드를 참고해서 필요할 때마다 직접 추가해주는 게 좋다고 생각합니다!

2024-06-23 13:59 UTC, hee-suh commented on src/components/KakaoMap.tsx
케밥 ㅋㅋㅋㅋㅋㅋㅋ 보통 URL에서 kebab case를 쓰는데, nextjs에서 file-system based router를 사용하고 있어서 자연스럽게 kebab case를 따르게 된 거 같아요~

Cf. https://nextjs.org/docs/app/building-your-application/routing/defining-routes

2024-06-23 14:00 UTC, Pridesd commented on src/components/KakaoMap.tsx
설명 감사합니다 희 선생님!

2024-06-23 16:05 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +        center: new window.kakao.maps.LatLng(33.450701, 126.570667),
2d23a62d8f9f9764372a225d3f403bd5026d03c6

적용했습니다!

2024-06-23 16:07 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +      window.kakao.maps.event.addListener(
b50eca9351afa2aea19a088d0987f4fa4543373f
이 map 자체가 컴포넌트를 반환하는 친구가 아니다보니 hook으로 분리했습니다. 
현재 디자인 상으로 marker만 나오고 오버레이는 따로 나타나지 않고 바텀시트로 넘기는 것 같더라고요.
그래서 일단 marker 추가와 특정 위치로 이동하는 로직을 설정했습니다.

2024-06-23 16:08 UTC, Pridesd commented on src/components/KakaoMap.tsx
> +const KakaoMap = () => {
b50eca9351afa2aea19a088d0987f4fa4543373f

2024-06-24 05:19 UTC, hee-suh commented on src/components/KakaoMap.tsx
> +      window.kakao.maps.event.addListener(
말씀하시는 오버레이가 정보 창(info window) 말씀하시는게 맞을까요?
네이버 맵과 카카오 맵 모두 오버레이에 마커, 정보 창, 도형, 지상 오버레이 등이 포함된다고 정의하고 있어서 여쭤봅니다!

Cf. https://navermaps.github.io/maps.js.ncp/docs/tutorial-1-Overlay-Overview.html

2024-06-24 05:25 UTC, hee-suh commented on src/app/cc/page.tsx
> +      />
이 부분을 `<Map />` 으로 추상화하는 건 어떨까요?

2024-06-24 06:34 UTC, HaJunRyu commented on src/components/KakaoMap.tsx
첨부해주신 링크가 routing에 관련된 문서라서 Component 파일들에 대한 컨벤션을 kebab-case로 가져가는거에 대한 내용인지는 모르겠네요ㅎㅎ 뭔가 컴포넌트 파일을 kebab-case로 가져가는걸 처음 본거 같아요! (물론 팀에서 정하기 나름이지만ㅎㅎ)

2024-06-24 06:54 UTC, hee-suh commented on src/components/KakaoMap.tsx
Next.js 예제에는 components 파일명 컨벤션으로 [kebab-case를 따르는 경우](https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing/app/%5Blang%5D/components)도 있고, PascalCase를 따르는 경우도 있더라구요~

[Next.js의 파일 컨벤션](https://nextjs.org/docs/app/api-reference/file-conventions)이 kebab-case니까, component도 같이 kebab-case로 가져가면 더 예쁠 거 같아서 제안해봤어요! 

`LongLongComponentName.tsx` vs `long-long-component-name.tsx` 저는 전자보다 후자가 더 가독성이 좋은 것 같더라고요 👀

2024-06-24 07:13 UTC, poiu694 approved these changes
좋아요~ 궁금한 부분만 질문했습니당~ 이제 kakao 맵 고도화하면서 점점 더 디벨롭 해보져!

2024-06-24 07:13 UTC, poiu694 commented on src/hooks/use-map.ts
> +const INITIAL_LAT_LNG = {
P3 여기서만 LAT_LNG로 줄여 쓴 이유가 있나요?

2024-06-24 07:13 UTC, poiu694 commented on src/hooks/use-map.ts
> +  const [map, setMap] = useState<kakao.maps.Map | null>(null)
P3 여기도 `window.kakao` 로 안하신 이유가 있을까요? 통일하면 좋을 것 같아서요!

2024-06-24 07:13 UTC, poiu694 commented on src/hooks/use-map.ts
> +      const moveLatLon = new kakao.maps.LatLng(
P3

1. `moveLatLon` LatLng 일 것 같아요!
2. move로 시작해서 메서드 같은 느낌이 드는데 값이네요.! 차라리 `nextLocation`과 같은 변수명은 어떨까요?

2024-06-24 07:13 UTC, poiu694 commented on src/hooks/use-map.ts
> +    if (containerRef.current) {
이런 부분은 Early Return 으로 가져가면 어떨까요? cc) @hee-suh

2024-06-24 07:13 UTC, poiu694 commented on src/hooks/use-map.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
lint를 끈 이유가 있을까요?

2024-06-24 07:36 UTC, Pridesd commented on src/components/KakaoMap.tsx
글쿤용 저는 항상 PascalCase를 쓰다보니 익숙치 않아서 쉽지 않네요 ㅋㅋ 이게 컴포넌튼지 함순지 잘 모르겠어서

2024-06-24 07:37 UTC, Pridesd commented on src/hooks/use-map.ts
> +const INITIAL_LAT_LNG = {
이거 고민했는데 역시 길게 쓰는 게 낫겠죠?

2024-06-24 07:45 UTC, Pridesd commented on src/hooks/use-map.ts
> +  const [map, setMap] = useState<kakao.maps.Map | null>(null)
![image](https://github.com/mash-up-kr/VitaminC_Web/assets/72875894/b5da8d8c-0a9a-440c-beca-1bb5ba1b10b3)
window로 했을 때 해당 에러가 나타납니다 ㅠ

2024-06-24 07:46 UTC, Pridesd commented on src/hooks/use-map.ts
> +  const [map, setMap] = useState<kakao.maps.Map | null>(null)
Winow는 위 에러가 나타나고 window는 해당 네임스페이스를 찾을 수 없다는 에러가 나타나요 ..

2024-06-24 07:48 UTC, poiu694 commented on src/hooks/use-map.ts
> +const INITIAL_LAT_LNG = {
네이밍에 대해서도 같이 생각해보면 좋을 것 같아요!

Coordination, GeoLocation 등 한 단어로 해도 좋고, 통일성만 있으면 좋습니다~

2024-06-24 07:49 UTC, poiu694 commented on src/hooks/use-map.ts
> +  const [map, setMap] = useState<kakao.maps.Map | null>(null)
type만 따로 정의해서 써도 동일한가요?

2024-06-24 07:50 UTC, poiu694 commented on src/hooks/use-map.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
기존 함수를 useCallback으로 감싸는건 어떨까요!?

2024-06-24 07:54 UTC, HaJunRyu commented on src/components/KakaoMap.tsx
어떤 방향이든 일관성 있게 지켜가면 문제는 없는거 같아요ㅎㅎ 다만 생태계에서 범용적으로 쓰는 패턴을 쓰면서 몸에 익는게 다른 프로젝트를 할때도 편하다고 생각되는건 있는거 같아서 그 측면에서 좀 더 범용적인 패턴을 컨벤션으로 가져가는걸 선호하는 사람입니다😎

2024-06-24 07:54 UTC, hee-suh commented on src/hooks/use-map.ts
> +const INITIAL_LAT_LNG = {
@Pridesd @poiu694 풀네임으로 통일할까요?!

2024-06-24 07:55 UTC, Pridesd commented on src/hooks/use-map.ts
> +const INITIAL_LAT_LNG = {
동의합니다~

2024-06-24 08:17 UTC, Pridesd commented on src/hooks/use-map.ts
> +  const [map, setMap] = useState<kakao.maps.Map | null>(null)
동일하네요 ..

2024-06-24 08:18 UTC, Pridesd commented on src/hooks/use-map.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
9552b577fd0d117426f96f36260bbfcf02086a51

2024-06-24 08:19 UTC, Pridesd commented on src/hooks/use-map.ts
> +    if (containerRef.current) {
4d43a9a8bcf4d535991a230df080f7011154e587

2024-06-24 08:19 UTC, Pridesd commented on src/hooks/use-map.ts
> +      const moveLatLon = new kakao.maps.LatLng(
56dda00714161c5ddc23e6a72a8b85637eee7cb8

2024-06-24 08:19 UTC, Pridesd commented on src/hooks/use-map.ts
> +const INITIAL_LAT_LNG = {
4b8fc16d3978ac2bcd439c70a7bbbbfbc2043e54

2024-06-24 08:36 UTC, Pridesd commented on src/app/cc/page.tsx
> +      />
a1f0090418b76f95de788abca322bc58249dcf74

Map이라는 이름이 불가능해서 MapBox로 만들어봤습니다!

2024-06-26 10:05 UTC, hee-suh commented on src/components/map-box.tsx
> +import React from 'react'
`import { forwardRef } from 'react';` 로 변경 요청드립니닷~!

2024-06-26 10:30 UTC, Pridesd commented on src/components/map-box.tsx
> +import React from 'react'
47e1da3e7e40bb3fc2bf1ad324cb805ae07b8a6a

2024-06-27 01:39 UTC, Pridesd reviewed
@poiu694  eventType에 실제 이벤트 리스너 타입 추가했어요!

2024-06-27 02:37 UTC, poiu694 reviewed
진짜진짜 거의 끝!

2024-06-27 02:37 UTC, poiu694 commented on src/hooks/use-map.ts
> +    [markerId in string]: kakao.maps.Marker
```ts
Record<string, kakao.maps.Marker> 타입은 어떨까요?
```

2024-06-27 02:37 UTC, poiu694 commented on src/hooks/use-map.ts
> +    })
이부분 업데이트 갱신이 잘 되나요? 불변성이 잘 안지켜진것 같아서요

2024-06-27 02:37 UTC, poiu694 commented on src/hooks/use-map.ts
> +    })
옹 초기화 전에 null로 바꾸는거 좋아요! 그런데 Object.values를 이용해도 되겠군요 :)

2024-06-27 03:01 UTC, Pridesd commented on src/hooks/use-map.ts
> +    })
[01d7144](https://github.com/mash-up-kr/VitaminC_Web/pull/18/commits/01d71449dccab819c8696e272dd5a50d44c587d3)

2024-06-27 03:01 UTC, Pridesd commented on src/hooks/use-map.ts
> +    [markerId in string]: kakao.maps.Marker
[8a4f70b](https://github.com/mash-up-kr/VitaminC_Web/pull/18/commits/8a4f70bd5df40e4e830d6bdc0e235b8d913d169f)

2024-06-27 03:01 UTC, Pridesd commented on src/hooks/use-map.ts
> +    })
[dfd7bce](https://github.com/mash-up-kr/VitaminC_Web/pull/18/commits/dfd7bced4084766c245f7167c4cb5f1628cba042)

2024-06-27 04:35 UTC, merged