feat: implement bottom sheet component
mash-up-kr/VitaminC_Web pull request #19
Opened 2024-06-23 07:32 UTC by hee-suh

## Issue Number

#16 

## Description

> 구현 내용 및 작업한 내용

기본 바텀 시트를 구현하였습니다.

- [x] default는 닫혀있는(collapsed) 상태로, 바텀시트의 헤더만 표시됩니다.
- [x] 헤더를 위로 당기면 바텀시트가 열립니다(expanded).
- [x] 열린(expanded) 바텀시트의 헤더를 아래로 당기거나, 바텀시트의 뒷부분에 해당하는 배경을 탭하면 바텀시트가 닫힙니다(collapsed).
- [x] props를 이용해 header의 콘텐츠, body의 콘텐츠(필수), 바텀 시트의 열림 여부(expanded)를 정할 수 있습니다.
- [x] 스토리북(`bottom-sheet.stories.ts`)에서 테스트 가능하며, `/cc`에서 사용 예제를 확인할 수 있습니다.

<img width="400" alt="스크린샷 2024-06-23 오후 4 31 31" src="https://github.com/mash-up-kr/VitaminC_Web/assets/53266682/e50baa66-d71f-4c09-904a-9cb20fb26487"> <img width="400" alt="스크린샷 2024-06-23 오후 4 31 40" src="https://github.com/mash-up-kr/VitaminC_Web/assets/53266682/2a9a6abc-583c-4e5e-87f5-05726836eac4">

## To Reviewers

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- `framer-motion`을 설치하여 이용하였습니다.
- 패키지 추가를 최소화하기 위해 [`react-use-measure`](https://www.npmjs.com/package/react-use-measure)`를 설치하지 않고, 코드를 참고하여 `useMeasure` hook을 만들었습니다.
그러면서 debounce 옵션과 [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)를 위한 polyfill 옵션도 빼게 되었습니다. (∵ debounce 패키지 추가 설치 필요 및 ResizeObserver class 선언으로 인한 타입 에러 이슈 발생)
- 바텀시트를 정말 잘 구현해둔 [`vaul`](https://github.com/emilkowalski/vaul)([`shadcn/ui`에서 import해서 사용](https://github.com/shadcn-ui/ui/blob/main/apps/www/components/drawer.tsx#L4)하고 있는 headless ui)을 보고 여러 가지 생각이 들었습니다.
   1. component library 설치 없이 바텀시트를 구현하고 싶어서, vaul과 유사하게 코드를 작성해보려고 했는데 vaul에서 [`radix-ui`의 dialog를 import](https://github.com/emilkowalski/vaul/blob/main/src/index.tsx#L3)하고 있어서, [이 블로그](https://velog.io/@sangpok/React-Bottom-Sheet#3-openedclosed-%EC%9C%84%EC%B9%98-%EC%9E%A1%EA%B8%B0)와 유사한 형태로 아주 간단한 형태의 바텀 시트를 구현하였습니다.
   2. 이렇게 제한된 기능만을 구현하는 데에도 시간이 꽤 소요되는데, `radix`나 `shadcn` 같이 잘 만들어져있는 라이브러리를 사용하는 게 나으려나... 라는 생각이 꽤나 여러 번 들었습니다. 😇
   3. 직접 구현에 대한 여러분의 생각이 궁금합니다. 💬

## Checklist

> PR 등록 전 확인한 것

- [x] 올바른 타켓 브랜치를 설정하였는가
- [x] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat: add login page`)
- [x] Description에 PR을 구체적으로 설명했는가

2024-06-24 04:03 UTC, Pridesd requested changes
고생 많으셨습니다! 접근성 관련해서 몇 가지 코멘트 남겼어요. 이건 접근성 관련해서 참고해볼만한 글입니다~!
https://www.inthepocket.design/articles/improving-the-accessibility-of-bottom-sheets

2024-06-24 04:03 UTC, Pridesd commented on src/components/bottom-sheet/index.tsx
> +      <motion.div
이 경우 bottom sheet 이외에 영역에도 키보드나 스크린리더로 접근이 가능할 것 같아서 그 부분을 막을 방법을 생각해보시면 좋을 것 같아요!
https://nuli.navercorp.com/community/article/1133093

2024-06-24 07:36 UTC, HaJunRyu reviewed
> - 이렇게 제한된 기능만을 구현하는 데에도 시간이 꽤 소요되는데, radix나 shadcn 같이 잘 만들어져있는 라이브러리를 사용하는 게 나으려나... 라는 생각이 꽤나 여러 번 들었습니다. 😇
> - 직접 구현에 대한 여러분의 생각이 궁금합니다. 💬

당연히 서비스를 만들때의 공수 측면으로는 잘 구현해놓은걸 쓰는게 좋다고 생각은 드나 직접 구현함으로써 얻을 수 있는 이점도 많다고 생각이 듭니다.
지금 생각되는건 당연히 라이브러리를 쓰지 않으니 번들 자체가 가벼워지는 이점도 있을거 같은데 사실 이건 `framer-motion`이 붙음으로써 그렇게까지 크게 다가오지는 않는거 같아요ㅋㅋㅋㅋ `framer-motion`없이 구현해봤으면 더 좋았을것도 같은데 이건 팀원들과의 선택의 문제이니~~

근데 사실상 더 큰 이점은 이런 UI Component들 구현하다보면 얻는 인사이트들이 굉장히 많은거 같아요, 해보지 않으면 감이 잘 오지 않는 UI Component들의 구현 방식과 설계 방식에 대해 생각할 수 있게 되는거 같고 그러다보면 생긴건 다른 UI여도 내부 로직 입장에서보니 비슷한 패턴이라면 구현이 가능할것 같은데? 에 대한 판단도 되고 그거 자체가 사고가 넓어진거라고 생각을 합니다 :)

라이브러리를 쓰지 않는다는건 당연히 공수를 더 많이 들여야하고 이슈도 많을 수 있을 수 있지만 그만큼 시간을 많이 쓰려고 하는거 같아서 본인과 팀이 감당할 수 있는선에서는 좋은거 같습니다 (이 선이 명확하지 않지만은ㅋㅋㅋㅋ) 근데 바텀시트 정도의 UI Component 단위들은 사실 그 선 안에 들어오지 않나? 싶긴하네요👍

2024-06-24 07:36 UTC, HaJunRyu commented on src/components/bottom-sheet/index.tsx
> +          <div className="m-[20px] text-[14px]">{header}</div>
header가 optional prop이던데 혹시 header값이 undefined 일때도 해당 라인 전체가 렌더링 되어야하나요~? margin이 들어가있어서 div가 렌더링되는건 의도된 동작 같기도 한데 혹시나 해서 코멘트 남깁니다~!

2024-06-24 07:36 UTC, HaJunRyu commented on src/components/bottom-sheet/index.tsx
> +          style={{ height: size?.height / 2 }}
optional chaining을 하면서 size.height를 참조하지 못한다면 `undefined / 2`가 될 수도 있을거 같은데 이때 결과가 `NaN`이 될거 같습니다! 적절한 예외처리를 추가해주면 어떨까요 :)

2024-06-24 07:36 UTC, HaJunRyu commented on src/hooks/use-measure.ts
> +export interface RectReadOnly {
해당 interface를 export 해준 이유가 있을까요~? 현재는 해당 파일내에서만 쓰이는것 같고 `react-use-measure`에서도 해당 interface를 export 하는 구문이 보이긴하는데 다른곳에서 쓰이고 있는지 보니 없는거 같던데 이게 외부에서 활용 될 일이 있을까요?

사실 라이브러리단에서는 네이밍 자체가 되게 도매인에 대해 무조건 안다고 가정하고 지은 느낌인거 같은데(실제로 특정 기능의 라이브러리이니 그게 맞기도 하고) 서비스 코드에서 이렇게 써있는데 export까지 되어있으니 다른 네이밍들과 헷갈릴 수 있는 요인이 될거 같다는 생각도 드는거 같아요..! (엄청 강한 의견의 리뷰는 아니고 어떤 생각인지 논의해보고 싶네요~~)

2024-06-24 07:36 UTC, HaJunRyu commented on src/hooks/use-measure.ts
> +  () => void,
여긴 VoidFunction으로도 사용이 가능할거 같네요! 근데 아마 이것도 라이브러리 코드를 그대로 쓴거 같아서 가벼운 의견 정도로만 생각해주세요ㅋㅋㅋㅋ

2024-06-24 07:36 UTC, HaJunRyu commented on src/hooks/use-window-size.ts
> +    }
지금 당장 해당 hook을 완벽하게 만들자는 아닌거 같긴한데 초기값은 `MIN_WIDTH`, `MIN_HEIGHT`인데 실제로 resize 이벤트를 발생시키다보면 MIN 값 보다 더 작은 값도 상태값으로 할당이 될 수 있어보이네요, 만약 지금의 동작이 의도된거라고 한다면 `MIN_WIDTH`, `MIN_HEIGHT`보단 `INITIAL_WIDTH`, `INITIAL_HEIGHT`라는 이름이 더 적절할거 같아요!

근데 만약 지금의 동작을 의도한게 아닌 진짜 MIN값을 유지하려는게 의도였다면 handleResize 함수에서 min값에 대한 예외처리를 해주면 좋을거 같습니다 :)

2024-06-24 07:36 UTC, HaJunRyu commented on src/hooks/use-window-size.ts
> +    window.addEventListener('resize', handleResize)
resize 이벤트는 이벤트 발생 빈도가 너무 높기 때문에 throttle을 적용하여 대략 200ms 내외의 간격으로만 이벤트를 발생시켜도 충분하지 않을가 싶기도 하네요 :) handleResize는 state를 변경하여 리렌더를 일으키기도 하니 UX에 영향이 없는 범위 정도로 throttle 해주면 어떨까합니다!

해당 리뷰를 남기는 라인이 handleResize 선언부가 맞을수도 있긴한데 일단 이벤트 add 하는 부분에서 생각이 들어서 여기에 남깁니다ㅋㅋㅋㅋ

2024-06-24 07:41 UTC, poiu694 reviewed
크~ 고생했어요!~~!

2024-06-24 07:41 UTC, poiu694 commented on src/components/bottom-sheet/bottom-sheet.stories.ts
> +const meta = {
스토리 좋아요~

2024-06-24 07:41 UTC, poiu694 commented on src/components/bottom-sheet/index.tsx
> +    () => Math.min(contentBounds.height + 50, size?.height),
size?.height 의 값이 없는 경우는 어떤건가요?

이게 오류를 범하진 않을까요? `Math.min(1, undefined) // NaN`

2024-06-24 07:41 UTC, poiu694 commented on src/components/bottom-sheet/index.tsx
> +          const offsetThreshold = 150
흠 이게 사실 drag 할 때 같이 움직이다가, 범위에 따라서 제일 가까운 정지 지점?(5분의 4지점 등)이 되는 등의 액션이 필요하면 바뀌긴 해야 할 것 같네요

2024-06-24 07:41 UTC, poiu694 commented on src/components/bottom-sheet/index.tsx
> +        onTap={() => setIsOpen(false)}
아래는 onPointerDown이고 여기서는 onTap인데 혹시 이유가 있을까용?

2024-06-24 07:41 UTC, poiu694 commented on src/components/bottom-sheet/index.tsx
> +          style={{ height: size?.height / 2 }}
여기도 size추론이 안 된 경우 위와 동일합니다~

2024-06-24 07:41 UTC, poiu694 commented on src/hooks/use-measure.ts
> +  [key: string]: number
key string으로 따로 받을 필요가 있을까요?

2024-06-24 07:41 UTC, poiu694 commented on src/hooks/use-measure.ts
> +    return () => void window.removeEventListener('resize', cb)
event를 넣어주는 훅을 따로 빼도 좋긴 하겠네여~

2024-06-24 07:41 UTC, poiu694 commented on src/hooks/use-measure.ts
> +  })
이런 부분도 훅으로 더 분리해도 좋을 것 같아요!

2024-06-24 07:41 UTC, poiu694 commented on src/hooks/use-measure.ts
> +    Object.freeze(size)
object.freeze를 하신 이유가 있나요? as const 정도로는 부족할까요?

2024-06-24 07:41 UTC, poiu694 commented on src/hooks/use-measure.ts
> +      state.current.element.getBoundingClientRect() as unknown as RectReadOnly
기존에 반환하는 DOMRect에서 as로 변환 한 이유가 있을까요?

2024-06-24 07:41 UTC, poiu694 commented on src/hooks/use-measure.ts
> +    // eslint-disable-next-line @typescript-eslint/no-use-before-define
린트를 끄신 이유가 궁금합니다~!

2024-06-24 07:41 UTC, poiu694 commented on src/hooks/use-measure.ts
> +    state.current.resizeObserver!.observe(state.current.element)
assert로 하신 이유가 궁금합니다~! 아래처럼 if로 감싸지 않은 이유가 있을까요~>!

2024-06-24 07:41 UTC, poiu694 commented on src/hooks/use-measure.ts
> +  }, [scroll, handleChange, handleChange, removeListeners, addListeners])
두 handleChange!

2024-06-24 07:41 UTC, poiu694 commented on src/hooks/use-measure.ts
> +  useEffect(() => removeListeners, [removeListeners])
unmount 시점은 한 번 더 return문으로 들어가야 하는거 아닌가여!? 주석이랑 동작이 헷갈려서요

2024-06-24 07:41 UTC, poiu694 commented on src/hooks/use-measure.ts
> +type Result = [
어떤 Result인지 조금더 명시해도 좋지 않을까요?!

2024-06-24 07:41 UTC, poiu694 commented on src/hooks/use-measure.ts
> +type State = {
이 부분 State도여! 나중에 State 검색했는데 각각 어떤건지 파악하는 것보다 부수적인 설명이 있으면 좋을 것 같아요! 취향적인 부분이긴 합니다~!!

2024-06-24 07:46 UTC, poiu694 commented
> 직접 구현에 대한 여러분의 생각이 궁금합니다. 💬

이 부분은 사실 해보고 싶은 부분이면 구현을 직접 해 보는게 사이드 플젝의 묘미 아닐까 싶어요! 처음부터 라이브러리에서 사용하는 것처럼 완벽하기엔 어려우니까, 플젝에서 만들어보고 테스트를 통해서 디벨롭해보는 것도 재미중에 하나라고 생각하거든요. 좋은 아이디어가 생긴다면 기존 라이브러리에 기여해볼 수 있는 경험도 생기고요!

대신에 너무 매몰되지만 않으면 좋을 것 같아요. 많은 부분을 신경써야 하니까 기간 산정이나 개발을 진행할 때 주의만 하면 좋을 것 같아요! 고도화하다가 힘들겠다 싶으면 라이브러리로 바꾸어도 좋습니다!

2024-06-24 08:07 UTC, HaJunRyu commented on src/hooks/use-measure.ts
> +  useEffect(() => removeListeners, [removeListeners])
화살표 함수 축약해서 써서 그런듯? 근데 가독성적으로 문제 있다고 생각되면 명시적으로 return 써주는것도 좋긴 하겠네요ㅎㅎ

2024-06-24 08:13 UTC, poiu694 commented on src/hooks/use-measure.ts
> +  useEffect(() => removeListeners, [removeListeners])
오호..? 아래처럼 안해도 되나??? 

```
  useEffect(
    () => () => {
      console.log('unmount');
    },
    []
  );

// 

 useEffect(() => {
    return () => {
      console.log('unmount');
    };
  }, []);
  ```

2024-06-24 08:18 UTC, hee-suh commented on src/hooks/use-measure.ts
> +  useEffect(() => removeListeners, [removeListeners])
아래처럼 블록`{}`이 없어서 `return` 생략한 거 같은데 보기 불편하네요...! [react-use-measure](https://www.npmjs.com/package/react-use-measure)를 거의 건드리지 않다보니 이런 일이... 수정 가겠습니닷~!

<img width="788" alt="스크린샷 2024-06-24 오후 5 16 12" src="https://github.com/mash-up-kr/VitaminC_Web/assets/53266682/c7d74426-3d4f-44b3-958f-ec5bf823bfd8">

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/Arrow_functions

2024-06-24 08:51 UTC, poiu694 commented on src/hooks/use-measure.ts
> +  useEffect(() => removeListeners, [removeListeners])
아 생각해보니까 반환값 리턴하는 함수니까 그렇긴 하네요! 감사합니다~

2024-06-24 14:44 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +      <motion.div
지도의 경우 바텀시트가 활성화되어도 배경이 그대로 보일뿐만 아니라, 클릭도 바텀시트가 닫혀있을 때와 마찬가지로 동작해야 하는데, 어떤 부분을 막아야 하는 걸까요?

2024-06-24 14:49 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +  )
오! 네 저 값은 memoization이 불필요한 것 같네요. 👍👍👍

2024-06-24 14:55 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +          onPointerDown={(e) => dragControls.start(e)}
이 경우에는 이벤트를 넘겨줘야 dragControls가 정상 작동해서 이렇게 작성해두었습니다~!

2024-06-24 14:59 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +          <div className="m-[20px] text-[14px]">{header}</div>
넵 header 유무와 상관 없이 어느 정도의 여백을 두기 위함이긴 했는데, header가 없는 경우에는 margin 대신 height가 있는 div를 배치하는 방식 등으로 변경하는게 더 낫겠네요!

2024-06-24 15:03 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +          style={{ height: size?.height / 2 }}
앗 optional chaining이 필요 없는 경우였는데 남발했네요. `useWindowSize()`에 항상 default 값이 있어서 `undefined`가 되는 경우가 발생하지 않을 것 같습니다.

2024-06-24 15:06 UTC, hee-suh commented on src/hooks/use-measure.ts
> +export interface RectReadOnly {
`use-measure.ts`에 있는 타입 export는 전부 제거해야겠어요! 그리고 네이밍도 전반적으로 수정해보도록 하겠습니다~!

2024-06-24 15:08 UTC, hee-suh commented on src/hooks/use-window-size.ts
> +    }
저희가 지원할 값들 안에서 resizing을 제한하기 위한 목적이어서, 예외 처리를 해줘야 할 것 같습니다!

2024-06-24 15:12 UTC, hee-suh commented on src/hooks/use-window-size.ts
> +    window.addEventListener('resize', handleResize)
아! [react-use-measure](https://www.npmjs.com/package/react-use-measure)에서 debounce 처리를 해뒀던데, 이러한 이유였겠네요. use-measure랑 같이 throttle 이든, debounce든 처리해보겠습니닷~!

Cf. https://github.com/pmndrs/react-use-measure/blob/master/src/web/index.ts#L70

2024-06-24 15:13 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +    () => Math.min(contentBounds.height + 50, size?.height),
`useWindowSize()`에 항상 default 값이 있어서 undefined가 되는 경우는 없을 것 같네요. optional chaining의 남용이었던 것... 제거할게요!

2024-06-24 15:14 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +          const offsetThreshold = 150
맞습니다. 상태를 여러 개로 나누려면 범위에 따라서 값을 바꿔줘야할 것 같습니다. 😇

2024-06-24 15:29 UTC, hee-suh commented on src/hooks/use-measure.ts
> +  () => void,
`VoidFunction`을 사용해본 적이 없고, [정보가 적은데](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.voidfunction.html) 보통 언제 사용하는지 알려주실 수 있나요?

저 부분을 VoidFunction으로 변경해주면, handleChange의 리턴도 VoidFunction으로 변경해줘야 하는데, 변경해주면 에러가 발생해서 용례를 알고 싶습니다!

<img width="787" alt="스크린샷 2024-06-25 오전 12 26 28" src="https://github.com/mash-up-kr/VitaminC_Web/assets/53266682/ab37bb79-6fbf-4623-9f86-3825cea6af66">
<img width="932" alt="스크린샷 2024-06-25 오전 12 25 52" src="https://github.com/mash-up-kr/VitaminC_Web/assets/53266682/982f26d3-912f-45d9-8b19-5c6f4e38e7f5">

Cf. https://github.com/microsoft/TypeScript/issues/58099 Function lacks ending return statement and return type does not include 'undefined'

2024-06-24 15:47 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +        onTap={() => setIsOpen(false)}
배경과 바텀시트 영역에서 각각 기능이 다른데, 각 기능에 가장 최적화되어있다고 생각한 콜백을 사용했습니다!
- 배경은 탭(`onTap`)했을 때 닫기
   Cf. https://www.framer.com/motion/gestures/#tap
- 바텀시트 영역 내부에서 바텀시트를 조절할 때는 드래그
  [framer-motion 문서에서 dragControls에는 onPointerDown을 사용](https://www.framer.com/motion/gestures/###dragcontrols)

2024-06-24 15:49 UTC, hee-suh commented on src/hooks/use-measure.ts
> +  [key: string]: number
export 하지 않고, 이 파일에서만 사용하는 걸로 수정할 예정이라 key도 따로 받을 필요가 없겠네요!

2024-06-24 15:49 UTC, hee-suh commented on src/hooks/use-measure.ts
> +    return () => void window.removeEventListener('resize', cb)
네! window 객체에 접근하는 것들은 모두 hook으로 빼보겠습니다~!

2024-06-24 15:50 UTC, hee-suh commented on src/hooks/use-measure.ts
> +  })
mount 여부 확인하는 훅도 따로 분리할게요!

2024-06-24 15:57 UTC, hee-suh commented on src/hooks/use-measure.ts
> +    Object.freeze(size)
```
size.height = state.current.element.offsetHeight
size.width = state.current.element.offsetWidth
```
size 선언 후 size를 변경해주고 있어서 변경 후에 Object.freeze를 했는데, size 선언 시 말고 변경 후 size에 as const를 적용하는 방법이 따로 있을까요?

2024-06-24 15:58 UTC, hee-suh commented on src/hooks/use-measure.ts
> +    // eslint-disable-next-line @typescript-eslint/no-use-before-define
커밋 올리고 발견해서 다음 커밋 때 스리슬쩍 삭제하려고 했는데 들켜버렸네요 ^^..

2024-06-24 16:14 UTC, hee-suh commented on src/hooks/use-measure.ts
> +    state.current.resizeObserver!.observe(state.current.element)
`!.`를 검색해보니 [Nullish coalescing operator (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing)의 축약이라고 하는 거 같은데 이걸 assert라고 부르는군요?!

아래는 어차피 scroll 여부도 확인해야 해서 if문으로 감쌌는데, 이 경우에는 
```
  if (state.current.resizeObserver) {
    state.current.resizeObserver.observe(state.current.element)
  }
  ```
보다 `!.`로 나타내는게 훨씬 간결해서 저렇게 사용한 것 같네요. 근데 이해하기 편하기 위해 if 문으로 감싸야겠습니다!

2024-06-24 23:50 UTC, poiu694 commented on src/hooks/use-measure.ts
> +  () => void,
```
type A = () => void;
type B = VoidFunction
```

2024-06-24 23:58 UTC, poiu694 commented on src/hooks/use-measure.ts
> +    state.current.resizeObserver!.observe(state.current.element)
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator

null이나 undefined 될 수 있는 부분을 강제로 아니라고 하는 문법이에요! as 키워드로 강제했을 때 타입이 오류날 수 있듯이, assertion도 확실한 부분이 아니라면 런타임 디버깅에서 좋습니다~

2024-06-24 23:58 UTC, poiu694 commented on src/hooks/use-measure.ts
> +    Object.freeze(size)
아 size를 바꾸는 부분이 있긴 하군용! 그래도 Object.freeze 로 감싸서 관리하는 이유가 있을까요?

불변 상태 관리의 용이성/가시성/안정성 용도일까요?  freeze를 해야 하는 부분이 필요한 부분인지 궁금해요~!

2024-06-25 06:11 UTC, hee-suh commented on src/hooks/use-measure.ts
> +    state.current.resizeObserver!.observe(state.current.element)
사실 [원본 코드](https://github.com/pmndrs/react-use-measure/blob/master/src/web/index.ts#L46)에서는 `ResizeObserver`가 없는 경우가 발생하지 않게끔 예외처리를 해줬는데, 

```typescript
declare type ResizeObserverCallback = (
  entries: any[],
  observer: ResizeObserver,
) => void
declare class ResizeObserver {
  constructor(callback: ResizeObserverCallback)
  observe(target: Element, options?: any): void
  unobserve(target: Element): void
  disconnect(): void
  static toString(): string
}

...

const ResizeObserver =
  polyfill || (typeof window === 'undefined' ? class ResizeObserver {} : (window as any).ResizeObserver)

if (!ResizeObserver) {
  throw new Error(
    'This browser does not support ResizeObserver out of the box. See: https://github.com/react-spring/react-use-measure/#resize-observer-polyfills'
  )
}
```

<img width="758" alt="스크린샷 2024-06-25 오후 3 08 21" src="https://github.com/mash-up-kr/VitaminC_Web/assets/53266682/2b3c2c6e-0af1-4522-8ddf-999aad6b2a9f">

타입 에러가 발생해서 해당 부분을 제거하는 바람에 의문이 생기는 코드가 되어버린 것 같네요...! 지금 amolang 터져라 코드가 되어버린 것 같은데 ResizeObserver를 처리하는 좋은 방법이 있을까요? 😢

2024-06-25 06:37 UTC, hee-suh commented on src/hooks/use-measure.ts
> +      state.current.element.getBoundingClientRect() as unknown as RectReadOnly
DOMRect가 extends 하는 DOMRectReadOnly에는 toJSON() 프로퍼티도 있어서, RectReadOnly를 명시한 것 같습니다! `as unknown`은 빼도 되겠네요!

<img width="880" alt="스크린샷 2024-06-25 오후 3 35 30" src="https://github.com/mash-up-kr/VitaminC_Web/assets/53266682/42ee8215-cce8-4544-ae2b-bc5fcc379f6e">

2024-06-25 06:39 UTC, HaJunRyu commented on src/components/bottom-sheet/index.tsx
> +          onPointerDown={(e) => dragControls.start(e)}
`dragControls.start` 자체가 함수라고 한다면 제가 제안한대로 작성하면 event는 함수로 전달되긴 합니다

onPointerDown에서 dragControls.start를 아래 수도코드처럼 호출한다고 생각하면 될거 같네요 :)

```tsx
function onPointerDown() {
  dragControls.start(event);
}
```

2024-06-25 06:39 UTC, hee-suh commented on src/hooks/use-measure.ts
> +    Object.freeze(size)
현재 코드 상으로는 size에 접근할 일이 없긴 한데, 말씀하신 용도가 맞는 것 같습니다!

2024-06-25 06:40 UTC, HaJunRyu commented on src/components/bottom-sheet/index.tsx
> +          <div className="m-[20px] text-[14px]">{header}</div>
저였으면 뭔가 div 자체에 주기보단 상위 레이아웃 단에서 gap을 이용해서 여백을 주고 불필요한 요소는 조건부 렌더링으로 아예 렌더링을 안할거 같긴한데 마이너한 리뷰라고 생각해주셔도 될거 같습니다ㅋㅋㅋㅋ

2024-06-25 06:41 UTC, HaJunRyu commented on src/components/bottom-sheet/index.tsx
> +          style={{ height: size?.height / 2 }}
좋습니닷 불필요한 optional chaning은 추후 코드를 읽는 사람을 위해 제거해주면 좋을거 같네요 :)

2024-06-25 06:45 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +          onPointerDown={(e) => dragControls.start(e)}
start 함수는 이렇게 작성되어있고, 
<img width="800" alt="스크린샷 2024-06-25 오후 3 44 22" src="https://github.com/mash-up-kr/VitaminC_Web/assets/53266682/29e32b40-eb49-4bc4-90f9-ecfffc171acc">

말씀해주신대로 작성하면 에러가 발생하는데, event가 전달되는 경우와 전달되지 않는 경우가 어떻게 나뉘는 건지 더 찾아봐야겠습니다...!
<img width="250" alt="스크린샷 2024-06-25 오후 3 43 33" src="https://github.com/mash-up-kr/VitaminC_Web/assets/53266682/0359b460-9844-440b-9cae-be5ab34e3596">

2024-06-25 06:47 UTC, HaJunRyu commented on src/hooks/use-measure.ts
> +  () => void,
상민님 작성해주신대로 그냥 `() => void`를 선언적으로 표현하기 위해 type으로 alias를 한번 해준 느낌으로 생각하면 될 듯 합니당

첨부하신대로 쓰면 useCallback의 callback function에 void function을 준것이니 맞지 않는것 같고 딱 리뷰한쪽에만 써도 될 것 같아요! (사실 첫 리뷰에 얘기했듯이 이게 더 선언적이고 깔끔하다고 생각이 드신다면 적용하면 되는 P3 정도의 의견입니다ㅋㅋㅋ)

2024-06-25 06:49 UTC, HaJunRyu commented on src/hooks/use-window-size.ts
> +    window.addEventListener('resize', handleResize)
넵 scroll이랑 resize는 이벤트 발생빈도가 잦아서 정말 꼭 필요한 경우를 제외하고는 최적화를 한번 해주는게 좋은거 같더라고요 :)

2024-06-25 06:51 UTC, poiu694 commented on src/hooks/use-measure.ts
> +    state.current.resizeObserver!.observe(state.current.element)
오잉 저 Type Error는 중복된 변수 방지 아닌가여?

```TS
// 혹은 다른 변수명
const resizeObserver = typeof === .... ResizeObserver 
```
이런식으로는 안되나요?

2024-06-25 06:53 UTC, poiu694 commented on src/hooks/use-measure.ts
> +      state.current.element.getBoundingClientRect() as unknown as RectReadOnly
구조분해할당에서는 toJSON을 안쓰니까 굳이 as로 타입을 강제할 필요는 없지 않을까해서요!

2024-06-25 06:55 UTC, poiu694 commented on src/hooks/use-measure.ts
> +    Object.freeze(size)
흠 기존 리액트를 사용하지 않고 js 모듈 상태 프로그래밍 해서 객체의 불변성을 따로 지켜주는 느낌도 아니라서, 바로 사용되는 부분이면 크게 필요 없을 것 같긴해요!

2024-06-25 06:58 UTC, poiu694 commented on src/hooks/use-measure.ts
> +    state.current.resizeObserver!.observe(state.current.element)
저거 다시 보는데  polyfill을 신경써줘야 할 수도 있겠네요..? 🤔

2024-06-25 07:01 UTC, HaJunRyu commented on src/components/bottom-sheet/index.tsx
> +      <motion.div
재석님이 이런 케이스를 얘기하신건지 잘 모르겠지만 제가 이해되기로는 bottom sheet가 실제 눈에 보이지 않을때도 DOM에 존재를 하니 screen-reader에 읽히거나 키보드의 tab 동작으로 접근이 가능하니 현재 bottom-sheet에서 구현하신 실제 UI적인 부분말고 그거와 분리하여 bottom-sheet가 현재 열려있는지에 대한 상태를 관리하여 해당 상태를 이용해 aria-hidden이나 tabIndex를 컨트롤 하면 좋을거 같다라는 생각이 드네요 (상태를 추가할지 기존 상태를 활용할지는 상황에 맞게!!)

해당 코드는 bottom sheet는 아니지만 위에서 말씀드린 접근성 관련 처리를 한 Toggle 가능한 Tab Component에서 aria-hidden과 tabIndex를 조절했던 코드입니다! 코드가 짧으니 간단히 참고 정도 해도 괜찮을듯 해요ㅋㅋㅋㅋ
https://github.com/mash-up-kr/mash-up-recruit-fe/blob/main/src/components/common/MyPageTab/MyPageTab.component.tsx#L20

2024-06-25 07:02 UTC, hee-suh commented on src/hooks/use-measure.ts
> +    state.current.resizeObserver!.observe(state.current.element)
<img width="783" alt="스크린샷 2024-06-25 오후 3 59 59" src="https://github.com/mash-up-kr/VitaminC_Web/assets/53266682/8ba67e70-7564-4a95-9c35-338a20eca3d3">

그렇게 하면 위 에러가 발생해서 다음과 같이 수정해야 하는데,
```typescript
const resizeObserver =
    typeof window === 'undefined'
      ? ResizeObserver
      : (window as any).ResizeObserver
```

기존 코드가 의도했던 class를 override하는 듯한 기능이 동일하게 작동하는지가 확실하지 않아서요!

2024-06-25 07:04 UTC, hee-suh commented on src/hooks/use-measure.ts
> +    state.current.resizeObserver!.observe(state.current.element)
react-use-measure 소스 코드에 있던 polyfill도 없애고 debounce도 없앴었는데, 이 정도면 그냥 저 라이브러리를 갖다쓰는게 맞는 것 같다는 생각도 스멀스멀... 드는군요... 🫠

2024-06-25 07:46 UTC, HaJunRyu commented on src/components/bottom-sheet/index.tsx
> +          onPointerDown={(e) => dragControls.start(e)}
일단 제가 제안드린대로 넘겨보면 event는 전달이 잘 되는데 (캡쳐 해주신건 코드를 어떻게 작성하신지 보여주시면 좋을거 같네요) this 바인딩 이슈 때문에 componentControls를 참조하지 못해 에러가 나네요
어쩔 수 없이 원래 작성하신대로 둬야할거 같습니다ㅎㅎ

DragControls의 start 함수는 아래처럼 작성되어 있습니당

```ts
start(event, options) {
        this.componentControls.forEach((controls) => {
            controls.start(event.nativeEvent || event, options);
        });
    }
```

2024-06-26 14:05 UTC, hee-suh commented on src/hooks/use-measure.ts
> +type Result = [
Result는 useMeasure 훅의 리턴 타입인데, 리턴 타입은 type으로 따로 선언하지 않고 바로 함수 내부에 적어주는 패턴이 많이 사용되는 방식인 것 같아서 그렇게 수정했습니다!

2024-06-26 14:06 UTC, hee-suh commented on src/hooks/use-measure.ts
> +type State = {
State는 useMeasure에서 관리하고 있는 state의 타입이라 그대로 유지하겠습니닷 ㅎ.ㅎ

2024-06-26 14:37 UTC, hee-suh commented on src/hooks/use-measure.ts
> +type Result = [
```typescript
const useMeasure = (
  { scroll, offsetSize }: Options = {
    scroll: false,
    offsetSize: false,
  },
): [(element: HTMLOrSVGElement | null) => void, RectReadOnly, () => void] => {
```

2024-06-27 09:25 UTC, Pridesd commented on src/components/bottom-sheet/index.tsx
> +      <motion.div
![image](https://github.com/mash-up-kr/VitaminC_Web/assets/72875894/9d94df91-8d7b-43ce-84c4-125a5b937885)
업로드한한 사진과 같이 바텀시트가 열려있는 경우에는 지도에 접근이 불가능해져야 돼요! 왜냐하면 바텀시트를 활성화 한 이유는 해당 바텀시트의 내용을 확인하기 위해 열었기 때문이죠. 그리고 대부분의 UI 상으로도 바텀시트 외부 요소를 클릭하게 되면 자동으로 바텀시트는 닫히도록 설정되어 있어요. 만약 바텀시트가 아닌 지도나 바텀시트 외부 요소에 접근하기 위해선 이미지 우측상단에 닫기 버튼 처럼 닫아야 사용이 가능하도록 바꿔야 할 것 같네요!

2024-06-27 15:36 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +          <div>{body}</div>
[fca9c22](https://github.com/mash-up-kr/VitaminC_Web/pull/19/commits/fca9c22311ccca35680424b7813471c47aff331c)

2024-06-27 15:37 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +        }}
[fca9c22](https://github.com/mash-up-kr/VitaminC_Web/pull/19/commits/fca9c22311ccca35680424b7813471c47aff331c)

2024-06-27 15:37 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +          <div className="w-[53px] h-[6px] bg-[#6D717A] my-0 mx-auto rounded-[999px]" />
디자인으로 어떻게 풀어낼 수 있을지 고민해보겠습니다!

2024-06-27 16:11 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +    () => Math.min(contentBounds.height + 50, size?.height),
[e989b36](https://github.com/mash-up-kr/VitaminC_Web/pull/19/commits/e989b3672e91023bc8325cdfa532ff35fa93f4b2)

2024-06-27 16:11 UTC, hee-suh commented on src/components/bottom-sheet/index.tsx
> +        }}
[e989b36](https://github.com/mash-up-kr/VitaminC_Web/pull/19/commits/e989b3672e91023bc8325cdfa532ff35fa93f4b2)

2024-06-28 06:26 UTC, Pridesd approved these changes
고생하셨습니다!

2024-06-28 06:30 UTC, merged