feat: initial route setting
mash-up-kr/VitaminC_Web pull request #25
Opened 2024-06-27 06:59 UTC by Pridesd

## Issue Number

#20 

## Description

> 구현 내용 및 작업한 내용
페이지 작업을 위한 라우트 세팅을 했습니다.

- [x] 라우트 세팅
- [x] searchParam이 필요한 부분을 연결

## To Reviewers

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 지도는 userId와 mapName을 query string을 통해 가지고 오도록 했습니다.
- 인트로(회원가입)의 경우 query string의 step을 통해 관리했습니다. 

## Checklist

> PR 등록 전 확인한 것

- [x] 올바른 타켓 브랜치를 설정하였는가
- [x] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat: add login page`)
- [x] Description에 PR을 구체적으로 설명했는가

2024-06-28 12:49 UTC, hee-suh requested changes
예외 처리까지 챙기셨네요! 고생하셨습니다!!!

2024-06-28 12:49 UTC, hee-suh commented on src/app/intro/page.tsx
> +export type IntroStep = 'nickname' | 'complete' | 'map' | 'invite'
type이 다른 곳에서도 쓰이는 경우에는 `models/interface.ts`에서 관리하는게 어떨까요?

2024-06-28 12:49 UTC, hee-suh commented on src/app/place/layout.tsx
> +  const searchParams = useSearchParams()
layout을 클라이언트 컴포넌트로 지정하는 것보다는, middleware에서 접근 권한을 조정하는 것도 좋을 것 같습니다!

2024-06-28 12:49 UTC, hee-suh commented on src/app/page.tsx
> +const Intro = () => {
`intro/page.tsx`와 이 파일의 관계가 어떻게 되나요?

2024-06-28 12:49 UTC, hee-suh commented on src/app/map/page.tsx
> +  if (!searchParams?.userId || !searchParams?.mapName) {
지도가 선택되지 않은 경우와 권한에 따른 접근 제어 모두 라우팅으로 처리하는게 어떨까요?

2024-06-28 12:49 UTC, hee-suh commented on src/app/search/page.tsx
> +    return <>지도 미선택</>
여기도 마찬가지로, 지도가 선택되지 않은 경우와 권한에 따른 접근 제어 모두 라우팅으로 처리하는게 어떨까요?

2024-06-28 23:15 UTC, Pridesd commented on src/app/page.tsx
> +const Intro = () => {
아 이 부분은 로그인 전 인트로 화면이라고 생각하고 Intro라고 한 건데요! 이름을 어떻게 지어야 할 지 모르겠어서 뒀습니다. 일단 Home으로 바꿔놓을게요.

2024-06-29 00:00 UTC, Pridesd commented on src/app/place/layout.tsx
> +  const searchParams = useSearchParams()
5b3164e92d8ba18183a8ea432487f6a9ddc83fef

2024-06-29 00:00 UTC, Pridesd commented on src/app/map/page.tsx
> +  if (!searchParams?.userId || !searchParams?.mapName) {
5b3164e92d8ba18183a8ea432487f6a9ddc83fef

2024-06-29 00:00 UTC, Pridesd commented on src/app/search/page.tsx
> +    return <>지도 미선택</>
5b3164e92d8ba18183a8ea432487f6a9ddc83fef

2024-06-29 00:01 UTC, Pridesd commented on src/app/intro/page.tsx
> +export type IntroStep = 'nickname' | 'complete' | 'map' | 'invite'
ef7a45b7c4f147ace4b83a01f61fa79e1314574d

2024-06-29 00:01 UTC, Pridesd commented on src/app/page.tsx
> +const Intro = () => {
b4977a21b344620bbb6af06abeebb873d61827b0

2024-06-29 04:40 UTC, hee-suh approved these changes
고생하셨습니다~!!!

2024-06-29 04:40 UTC, merged