feat: search page
mash-up-kr/VitaminC_Web pull request #44
Opened 2024-07-03 08:49 UTC by poiu694

## Issue Number

#26

## Description

> 구현 내용 및 작업한 내용

![image](https://github.com/mash-up-kr/VitaminC_Web/assets/43488305/f30028ef-ef74-4ba9-bd2e-325b9cf1949a)

## Checklist

> PR 등록 전 확인한 것

- [x] 올바른 타켓 브랜치를 설정하였는가
- [x] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat: add login page`)
- [x] Description에 PR을 구체적으로 설명했는가

2024-07-03 09:04 UTC, Pridesd reviewed
엄청 빠르시네요..
![image](https://github.com/mash-up-kr/VitaminC_Web/assets/72875894/8183d0d6-63ea-45f4-b22b-8a9527d3222b)

2024-07-03 09:04 UTC, Pridesd commented on src/app/search/page.tsx
> +        onChange={(e) => setQuery(e.target.value)}
P3: 값을 입력하면 이에 따른 자동완성 API를 계속 호출해야 되는데 변경이 일어날 때마다 query를 설정하면 너무 과하게 API를 호출하는 건 아닌지 생각이 드네요! debounce를 적용하는 건 어떻게 생각하시나요?

2024-07-03 09:04 UTC, Pridesd commented on src/app/search/search-form.tsx
> +            label: '인풋 지우기',
'입력 내용 지우기'를 추천드립니다.. ㅎㅎ 
접근성 지침 중에 가급적 외래어 사용을 지양한다도 있거든요!

2024-07-03 11:13 UTC, hee-suh requested changes
키워드 관리 넘 깔끔하네요 🥹 기획 반영 덜 된 것들 리뷰 남겨두었습니다~!

2024-07-03 11:13 UTC, hee-suh commented on src/app/search/page.tsx
> +    query === '' && !!recentKeywords.length && !!search
search가 없는 경우에도(search 페이지에 진입하자마자) isShowRecentKeywords가 활성화되어야 할 것 같아서 `&& !!search`는 제거해야할 것 같습니다!

2024-07-03 11:13 UTC, hee-suh commented on src/app/search/recent-keywords.tsx
> +        {recentKeywords.map((keyword, index) => (
<img width="300" alt="스크린샷 2024-07-03 오후 8 10 31" src="https://github.com/mash-up-kr/VitaminC_Web/assets/53266682/90544598-4106-4f2a-a5c1-3acb9e4a3c97">

가장 최근 검색어가 좌측부터 노출되어야 해서, `reverse()`를 추가해야할 것 같습니다!

2024-07-03 11:13 UTC, hee-suh commented on src/app/search/recent-keywords.tsx
> +            onClick={() => onDeleteKeyword(index)}
두 영역으로 나눠서 다음과 같이 수행되도록 해야할 것 같습니다!
- 검색어 클릭 시, 해당 식당이 선택된 “검색결과 - 지도에서 보기" 화면으로 이동
- x 클릭 시, onDeleteKeyword(index)

2024-07-03 23:59 UTC, poiu694 commented on src/app/search/page.tsx
> +    query === '' && !!recentKeywords.length && !!search
이거는 그 결과 api 나오면 연동하려고 하긴 했는데여!

0. search 페이지에 진입하자마자는 search에 빈 값으로 recent keyword가 뜸

1. search 키워드가 입력되어서 들어온 경우는 검색을 한 경우로 취급
2. recent keyword가 보이지 않고 결과 컴포넌트가 보이게 하기 위함

라우팅이 `/search` 만 만들어져있길래 result 여부 검사를 서치 파람으로 하려고 했는데 라우팅을 나누는게 좋을까요?

2024-07-04 00:09 UTC, poiu694 commented on src/app/search/page.tsx
> +        onChange={(e) => setQuery(e.target.value)}
이 부분은 onChange에서 다루는 것보다 api 호출쪽에서 debounce를 하는게 맞을 것 같아요!

2024-07-04 00:21 UTC, poiu694 commented on src/app/search/recent-keywords.tsx
> +        {recentKeywords.map((keyword, index) => (
reverse는 연산이 무거울 것 같아서 추가할 때 앞에 추가하는 방식으로 바꾸었어요~

2024-07-04 00:21 UTC, poiu694 commented on src/app/search/recent-keywords.tsx
> +            onClick={() => onDeleteKeyword(index)}
오 이거하려다가 까먹었네용 감사합니다~

2024-07-04 00:54 UTC, poiu694 commented on src/app/search/page.tsx
> +    query === '' && !!recentKeywords.length && !!search
아 이거 결과 페이지가 따로 있었군요! 결과인줄 알았던게 자동완성이였군.....

2024-07-04 05:24 UTC, hee-suh commented on src/app/search/page.tsx
> +      setRecentKeywords([keyword, ...existRecentKeywords])
구우우우우욷!

2024-07-04 05:38 UTC, hee-suh commented on src/app/search/page.tsx
> +  if (isServer) return <div>검색 페이지 로딩 중...</div>
이 방식으로 하면 Suspense가 작동하나요 ?_?

2024-07-04 05:43 UTC, hee-suh approved these changes
비타민C(은)는 깔끔한 검색 로직(을)를 얻었다!

![포켓몬스터](https://news.skhynix.co.kr/hs-fs/hubfs/B_NewsRoom/Technology(362)/%EB%B0%98%EB%8F%84%EC%B2%B4(216)/2018/1207/%EA%B8%B0%EC%A1%B4%20%EA%B2%8C%EC%9E%84%EC%97%90%EC%84%9C%EB%8A%94%20%EB%8B%A8%EC%88%9C%ED%9E%88%20%EB%AA%AC%EC%8A%A4%ED%84%B0%EB%B3%BC%EC%9D%84%20%EC%84%A0%ED%83%9D%ED%95%B4%20%EB%8D%98%EC%A7%80%EB%8A%94%20%EA%B2%83%EC%9D%B4%20%EC%A0%84%EB%B6%80%EC%98%80%EC%A7%80%EB%A7%8C.gif?width=1000&name=%EA%B8%B0%EC%A1%B4%20%EA%B2%8C%EC%9E%84%EC%97%90%EC%84%9C%EB%8A%94%20%EB%8B%A8%EC%88%9C%ED%9E%88%20%EB%AA%AC%EC%8A%A4%ED%84%B0%EB%B3%BC%EC%9D%84%20%EC%84%A0%ED%83%9D%ED%95%B4%20%EB%8D%98%EC%A7%80%EB%8A%94%20%EA%B2%83%EC%9D%B4%20%EC%A0%84%EB%B6%80%EC%98%80%EC%A7%80%EB%A7%8C.gif)

2024-07-04 06:00 UTC, poiu694 commented on src/app/search/page.tsx
> +  if (isServer) return <div>검색 페이지 로딩 중...</div>
빌드시 (서버단) 에러가 나지 않게 하기 위함입니다!

Suspense fallback을 제대로 줘야 서버단 클라이언트단이 같을 것 같은데 아직 로딩 컴포넌트나 이런게 나오지 않아서 저렇게만 두었어요~

2024-07-04 06:07 UTC, hee-suh commented on src/app/search/page.tsx
> +  if (isServer) return <div>검색 페이지 로딩 중...</div>
아하 이해했습니다~!!

2024-07-04 06:33 UTC, merged