feat: set map input modal
mash-up-kr/VitaminC_Web pull request #68
Opened 2024-07-21 06:49 UTC by Pridesd

## Issue Number

#66 

## Description

지도 정보 모달을 구현했습니다. 
![image](https://github.com/user-attachments/assets/5441f858-34ea-44b2-ad15-fb7b5a8d2191)
![image](https://github.com/user-attachments/assets/dcab3f00-f5c6-4777-a2ce-5dedbeaeece0)

> 구현 내용 및 작업한 내용

- [x] 지도 정보 모달 제작
- [x] 초대장 모달 제작

## To Reviewers

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 모달 백그라운드 클릭 수정

## Checklist

> PR 등록 전 확인한 것

- [ ] 올바른 타켓 브랜치를 설정하였는가
- [ ] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat: add login page`)
- [ ] Description에 PR을 구체적으로 설명했는가

2024-07-21 13:49 UTC, poiu694 approved these changes
![image](https://github.com/user-attachments/assets/b6253700-0ae5-4c4c-87ab-cb7520de8cc3)

2024-07-21 13:49 UTC, poiu694 commented on src/components/common/Modal/Modal.tsx
> +        console.log(event.target)
~

2024-07-21 13:49 UTC, poiu694 commented on src/types/api/maps.ts
> +  role: string
Role 타입 있지 않나여?

2024-07-22 01:03 UTC, Pridesd commented on src/components/common/Modal/Modal.tsx
> +        console.log(event.target)
776966172f11c6d52021f5ef5ad697afd7353571

2024-07-22 01:04 UTC, Pridesd commented on src/types/api/maps.ts
> +  role: string
921e6c07ecf04d8e3db689f703bd9bb03b6e0776
MapInfo랑 형태가 동일해서 제거했습니다!

2024-07-22 06:57 UTC, hee-suh requested changes
![image](https://github.com/user-attachments/assets/d67625e9-391c-473f-af03-c0ba5ebb1cda)

2024-07-22 06:57 UTC, hee-suh commented on src/components/boarding-pass/boarding-members.tsx
> +            // TODO: 사용자 정보 cookie에 저장하는 로직 완성 후 적용
사용자 정보는 `GET /users/me` 에서 받아오면 될 것 같아요~!

2024-07-22 06:57 UTC, hee-suh commented on src/models/map.interface.ts
> +export interface MapUser {
MapUser, UserByMap, MapInfo가 헷갈리는데 정리해주실 수 있나요?

2024-07-22 06:57 UTC, hee-suh commented on src/app/map/[mapId]/map-info-modal.tsx
> +  const [invitedCode, setInvitedCode] = useState<InviteLink>()
`invitedCode` -> `inviteCode`로 변경하고, `InviteLink` 대신에 `inviteLInk.token`만 저장해주실 수 있나요? 저는 이전에 inviteCode에는 token만 저장했었는데 코드 일관성이 있으면 좋을 것 같아서요!

2024-07-22 06:57 UTC, hee-suh commented on src/components/boarding-pass/boarding-info-pass.tsx
> +  // TODO: 사용자 정보 cookie에 저장하는 로직 완성 후 적용
여기도 사용자 정보는 `GET /users/me` 에서 받아오면 될 것 같아요~!

2024-07-22 06:57 UTC, hee-suh commented on src/components/boarding-pass/boarding-info-pass.tsx
> +  }, [mapId])
props 변경이 Effect deps로 들어가는 건 지양하면 좋을 것 같은데, `isInvited` 상태 대신, `const isInvited = !mapId`로 지정하면 정상 작동하지 않나요?

2024-07-22 06:57 UTC, hee-suh commented on src/components/boarding-pass/boarding-info-pass.tsx
> +  const isMyBoard = members.some(
그리고 여기에서는 'ADMIN'인지 여부만 확인하면 될 것 같습니다!

2024-07-22 12:34 UTC, Pridesd commented on src/components/boarding-pass/boarding-info-pass.tsx
> +  const isMyBoard = members.some(
그렇게 되면 멤버 중에 ADMIN 권한이 한명이라도 있는 경우에 isMyBoard가 활성화되기 때문에, 사용자 id도 확인하는 게 맞는 것 같아요!

2024-07-22 13:17 UTC, hee-suh commented on src/components/boarding-pass/boarding-info-pass.tsx
> +  const isMyBoard = members.some(
위에서 사용자 정보를 가져올 때 id 뿐만 아니라 사용자의 role까지 같이 오니까, users에서 map을 돌리는게 아니라 해당 사용자의 role만 체크하면 될 것 같아서요~!

2024-07-22 13:18 UTC, hee-suh commented on src/components/boarding-pass/boarding-info-pass.tsx
> +  const isMyBoard = members.some(
그리고 나중에는 방장뿐만 아니라 ADMIN인 경우에는 모두 초대가 가능하기 때문에, 방장 id와 일치하는지 여부는 확인할 필요가 없어서요!

2024-07-22 13:25 UTC, Pridesd commented on src/app/map/[mapId]/map-info-modal.tsx
> +  const [invitedCode, setInvitedCode] = useState<InviteLink>()
그러면 만료 시간도 따로 저장해놓을게요!

2024-07-22 13:47 UTC, Pridesd commented on src/app/map/[mapId]/map-info-modal.tsx
> +  const [invitedCode, setInvitedCode] = useState<InviteLink>()
a386afb4597deaeb7a754cbe66f1e2c474f29432

2024-07-22 13:47 UTC, Pridesd commented on src/components/boarding-pass/boarding-info-pass.tsx
> +  const isMyBoard = members.some(
d8bab11ce168fccd1ad7759f93990c880f7eddad

2024-07-22 13:47 UTC, Pridesd commented on src/components/boarding-pass/boarding-info-pass.tsx
> +  // TODO: 사용자 정보 cookie에 저장하는 로직 완성 후 적용
72497ae75b04a0b9096ca8b8fb1c00fbd1314d8d

2024-07-22 13:47 UTC, Pridesd commented on src/models/map.interface.ts
> +export interface MapUser {
c43fbb0c440a3d3b4b21f5b842077af024f71f00

2024-07-22 14:26 UTC, hee-suh commented on src/components/boarding-pass/boarding-info-pass.tsx
> +  }, [mapId])
아하 이렇게 되면 한 번 발급받은 초대장이 만료되기 전까지 같은 초대장을 사용하는 게 아니라, 지도를 바꿀 때마다 초대장을 새로 발급하는 형태군용

2024-07-23 00:41 UTC, hee-suh approved these changes
![image](https://github.com/user-attachments/assets/4e3fe92b-3f8e-4919-ace2-a033cc1235f9)

2024-07-23 00:55 UTC, merged