feat: set like api at map page and remove regacy
mash-up-kr/VitaminC_Web pull request #75
Opened 2024-07-26 14:15 UTC by Pridesd

## Description
지도 페이지 내 좋아요 기능과 사용하지 않는 부분 제거

> 구현 내용 및 작업한 내용

- [x] 사용하지 않는 부분 제거
- [x] 좋아요 기능 적용

## To Reviewers

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 낙관적 업데이트를 적용하고 싶은데 방법 조언 부탁드립니다!

## Checklist

> PR 등록 전 확인한 것

- [ ] 올바른 타켓 브랜치를 설정하였는가
- [ ] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat: add login page`)
- [ ] Description에 PR을 구체적으로 설명했는가

2024-07-26 15:01 UTC, hee-suh requested changes
낙관적 업데이트는 `isLike`를 state로 관리하고, `handleClick`이 실행될 때 바로 `isLike`의 상태를 변경해준 후, api 호출이 실패하면 catch 문에서 `isLike`의 상태를 원상복구해주면 될 것 같아요~!

2024-07-27 01:41 UTC, Pridesd commented on src/app/map/[mapId]/place-list-bottom-sheet.tsx
> +              onClickLike: () => handleLike(place),
8bd55dd6e3505d9eb748504c177ee39b15212e84

2024-07-27 01:50 UTC, Pridesd commented on src/components/place/place-map-popup.tsx
> +    }
8bd55dd6e3505d9eb748504c177ee39b15212e84

2024-07-27 01:50 UTC, Pridesd commented on src/app/map/[mapId]/place-list-bottom-sheet.tsx
> +              onClickLike: () => handleLike(place),
c07b3af5261edd1f18c304ccd9483a051413a725

2024-07-27 04:07 UTC, hee-suh approved these changes
![image](https://github.com/user-attachments/assets/1c86e850-1a2b-4186-b619-32ac900e08dd)

2024-07-27 05:01 UTC, poiu694 approved these changes

2024-07-27 05:02 UTC, merged